project_id = "cwqddjrmbhlyhldepytk"

[functions.send-contact-email]
verify_jwt = false

[functions.generate-image-description]
verify_jwt = true

[functions.generate-service-description]
verify_jwt = true
